### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-T16-4/main#206]
**Describe the bug**
Wrong error message shown when entering addRecruitmentPost.
Error shown max length is 10 but user guide shows max length is 20.
System accepts up to 20 characters.

**Expected behavior**
Should display the correct number

<hr>

**Reported by:** @angwm
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#420]</sub>

**Comment by ryanchen2018** [comment]
This is not exactly a bug but more of a mismatch/typo in message output. And the user guide has updated the range of job position up to 20 characters long which is the prioritized manual that user should follow. Anyway, I will update the message to tally the user guide. Thanks for your suggestion.
